name: Docker Build and Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t timane/imagechatbot:latest .

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push timane/imagechatbot:latest

      - name: Execute Python scripts in Docker container
        run: docker run timane/imagechatbot:latest python /app/preprocess.py

      - name: Execute training script
        run: docker run timane/imagechatbot:latest python /app/train_model.py

      - name: Execute prediction script (optional)
        run: docker run timane/imagechatbot:latest python /app/predict_response.py

      - name: Clean up
        run: docker system prune --force

    services:
      chatbot:
        image: timane/imagechatbot:latest
        ports:
          - 5000:5000
        options: --name chatbot
